'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class DocumentSearch
    
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    Protected WithEvents ddlDocType As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtUserCode As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtJID As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtAPNumFrom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtAPNumTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPIDFrom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPIDTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlDocStatus As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlApprovalStatus As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtDocDateFrom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDocDateTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDueDateFrom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDueDateTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtTaxDateFrom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtTaxDateTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtCardCodeFrom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtCardCodeTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtCardName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rblCardNameMode As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rblCommentsMode As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents ddlSortBy As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents rblSortOrder As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents ddlPageSize As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblResultCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents gvResults As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents btnDummyRemarks As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpeRemarks As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlRemarks As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnCloseRemarks As Global.System.Web.UI.WebControls.Button
End Class
