'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class PurchaseRequestForm

    Protected WithEvents lblCurrentUser As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents lnkHome As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    Protected WithEvents hfRateDate As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents lblDocNum As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDocStatus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtReqName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlReqDept As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtCardCode As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSearchCardCode As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblVendorInfo As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtCardName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSearchCardName As Global.System.Web.UI.WebControls.Button
    Protected WithEvents ddlDocCurrency As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtDocRate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnRefreshRate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents txtJID As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDocDate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents lblErrDocDate As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtReqDate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents lblReqDateHint As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtStatusDisplay As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtApprovalStatus As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtUPID As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnAddLine As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDeleteLine As Global.System.Web.UI.WebControls.Button
    Protected WithEvents fileUpload As Global.System.Web.UI.WebControls.FileUpload
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button
    Protected WithEvents gvAttachments As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents gvPRDetail As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents ddlPurchaser As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtOwner As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents lblDocTotalWithTax As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDocTotal As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblVatSum As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlApproval As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents txtApprovalComments As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnApprove As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnReject As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnExportPDF As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnNewDocument As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnDummy As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpeVendor As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlVendorSearch As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnCloseVendor As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents txtVendorSearchKeyword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnDoSearchVendor As Global.System.Web.UI.WebControls.Button
    Protected WithEvents hfSearchSource As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents rblSearchMode As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents gvVendorSearch As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents btnItemDummy As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpeItem As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlItemSearch As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnCloseItem As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents txtItemSearchKeyword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnDoSearchItem As Global.System.Web.UI.WebControls.Button
    Protected WithEvents hfItemSearchRowIndex As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents rblItemSearchMode As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents gvItemSearch As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents btnValidationDummy As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpeValidation As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlValidation As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents divValidationHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents btnValidationClose As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents pnlErrors As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents blErrors As Global.System.Web.UI.WebControls.BulletedList
    Protected WithEvents pnlWarnings As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents blWarnings As Global.System.Web.UI.WebControls.BulletedList
    Protected WithEvents btnValidationBack As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnValidationConfirm As Global.System.Web.UI.WebControls.Button
    Protected WithEvents hfOriginalReqDate As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents hfAdjustedReqDate As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents btnHolidayDummy As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpeHoliday As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlHoliday As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnHolidayClose As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents lblHolidayOriginalDate As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblHolidayName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblHolidayNextWorkday As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnHolidayKeep As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnHolidayAdjust As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnPriceUpdateDummy As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpePriceUpdate As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlPriceUpdate As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnPriceUpdateClose As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents btnPriceUpdateCancel As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnPriceUpdateConfirm As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblSelectedVendor As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnTextEditDummy As Global.System.Web.UI.WebControls.Button
    Protected WithEvents mpeTextEdit As Global.AjaxControlToolkit.ModalPopupExtender
    Protected WithEvents pnlTextEdit As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblTextEditTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtTextEditContent As Global.System.Web.UI.WebControls.TextBox

End Class
