USE [MDR]
GO

/****** Object:  Table [dbo].[MGUIAPDetail_Import]    Script Date: 2025/10/17 ¤W¤È 10:39:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MGUIAPDetail_Import](
	[ID] [int] NOT NULL,
	[LineId] [int] NOT NULL,
	[U_DocEntry] [int] NOT NULL,
	[U_OBJTYPE] [int] NOT NULL,
	[U_BELNR] [nvarchar](10) NOT NULL,
	[U_BLDAT] [datetime] NOT NULL,
	[U_VATDATE] [datetime] NOT NULL,
	[U_STCEG] [nvarchar](10) NOT NULL,
	[U_XBLNR] [nvarchar](16) NOT NULL,
	[U_ZFORM_CODE] [nvarchar](2) NOT NULL,
	[U_HWBAS] [numeric](19, 6) NOT NULL,
	[U_HWSTE] [numeric](19, 6) NOT NULL,
	[U_TAX_TYPE] [char](1) NOT NULL,
	[U_CUS_TYPE] [char](1) NOT NULL,
	[U_AM_TYPE] [char](1) NOT NULL,
	[U_VATCODE] [nvarchar](8) NOT NULL,
	[U_BUKRS] [nvarchar](20) NOT NULL,
	[U_FA_DESC] [nvarchar](40) NULL,
	[U_FA_QTY] [numeric](19, 6) NULL,
	[U_FA_USE] [nvarchar](100) NULL,
	[U_GatherMark] [char](1) NULL,
	[U_ConsolidQty] [numeric](19, 6) NULL,
	[U_MWSKZ] [nvarchar](3) NOT NULL,
	[U_LIFNR] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_MGUIAPDetail_Import] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[LineId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] ADD  CONSTRAINT [DF_MGUIAPDet_Import_U_OBJTYPE]  DEFAULT ((18)) FOR [U_OBJTYPE]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] ADD  CONSTRAINT [DF_MGUIAPDet_Import_U_VATCODE]  DEFAULT (N'100') FOR [U_VATCODE]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] ADD  CONSTRAINT [DF_MGUIAPDet_Import_U_BUKRS]  DEFAULT (N'100') FOR [U_BUKRS]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] ADD  CONSTRAINT [DF_MGUIAPDet_Import_U_FA_QTY]  DEFAULT ((0)) FOR [U_FA_QTY]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] ADD  CONSTRAINT [DF_MGUIAPDet_Import_U_GatherMark]  DEFAULT ('N') FOR [U_GatherMark]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] ADD  CONSTRAINT [DF_MGUIAPDet_Import_U_ConsolidQty]  DEFAULT ((0)) FOR [U_ConsolidQty]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import]  WITH CHECK ADD  CONSTRAINT [FK_MGUIAPDetail_Import_Header] FOREIGN KEY([ID])
REFERENCES [dbo].[MGUIAP_Import] ([ID])
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] CHECK CONSTRAINT [FK_MGUIAPDetail_Import_Header]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import]  WITH CHECK ADD  CONSTRAINT [CK_MGUIAPDet_Import_AM_TYPE] CHECK  (([U_AM_TYPE]='6' OR [U_AM_TYPE]='5' OR [U_AM_TYPE]='4' OR [U_AM_TYPE]='3' OR [U_AM_TYPE]='2' OR [U_AM_TYPE]='1'))
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] CHECK CONSTRAINT [CK_MGUIAPDet_Import_AM_TYPE]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import]  WITH CHECK ADD  CONSTRAINT [CK_MGUIAPDet_Import_CUS_TYPE] CHECK  (([U_CUS_TYPE]='2' OR [U_CUS_TYPE]='1' OR [U_CUS_TYPE]='0'))
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] CHECK CONSTRAINT [CK_MGUIAPDet_Import_CUS_TYPE]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import]  WITH CHECK ADD  CONSTRAINT [CK_MGUIAPDet_Import_TAX_TYPE] CHECK  (([U_TAX_TYPE]='3' OR [U_TAX_TYPE]='2' OR [U_TAX_TYPE]='1'))
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] CHECK CONSTRAINT [CK_MGUIAPDet_Import_TAX_TYPE]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import]  WITH CHECK ADD  CONSTRAINT [CK_MGUIAPDet_Import_U_OBJTYPE] CHECK  (([U_OBJTYPE]=(18)))
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] CHECK CONSTRAINT [CK_MGUIAPDet_Import_U_OBJTYPE]
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import]  WITH CHECK ADD  CONSTRAINT [CK_MGUIAPDet_Import_ZFORM_CODE] CHECK  (([U_ZFORM_CODE]=N'28' OR [U_ZFORM_CODE]=N'27' OR [U_ZFORM_CODE]=N'26' OR [U_ZFORM_CODE]=N'25' OR [U_ZFORM_CODE]=N'22' OR [U_ZFORM_CODE]=N'21'))
GO

ALTER TABLE [dbo].[MGUIAPDetail_Import] CHECK CONSTRAINT [CK_MGUIAPDet_Import_ZFORM_CODE]
GO


