USE [MDR]
GO

/****** Object:  Table [dbo].[MGUIAP_Import]    Script Date: 2025/10/17 ¤W¤È 10:39:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MGUIAP_Import](
	[ID] [int] NOT NULL,
	[LineId] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateBy] [nvarchar](50) NOT NULL,
	[UpdateDate] [datetime] NOT NULL,
	[UpdateBy] [nvarchar](50) NOT NULL,
	[U_DocEntry] [int] NOT NULL,
	[U_OBJTYPE] [nvarchar](10) NOT NULL,
	[DocNum] [int] NOT NULL,
	[DocTotal] [numeric](19, 6) NOT NULL,
	[VatSum] [numeric](19, 6) NOT NULL,
 CONSTRAINT [PK_MGUIAP_Import] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_MGUIAP_Import_ID_Line] UNIQUE NONCLUSTERED 
(
	[ID] ASC,
	[LineId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MGUIAP_Import] ADD  CONSTRAINT [DF_MGUIAP_Import_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[MGUIAP_Import] ADD  CONSTRAINT [DF_MGUIAP_Import_UpdateDate]  DEFAULT (getdate()) FOR [UpdateDate]
GO

ALTER TABLE [dbo].[MGUIAP_Import] ADD  CONSTRAINT [DF_MGUIAP_Import_U_OBJTYPE]  DEFAULT (N'18') FOR [U_OBJTYPE]
GO

ALTER TABLE [dbo].[MGUIAP_Import]  WITH CHECK ADD  CONSTRAINT [CK_MGUIAP_Import_U_OBJTYPE] CHECK  (([U_OBJTYPE]=N'18'))
GO

ALTER TABLE [dbo].[MGUIAP_Import] CHECK CONSTRAINT [CK_MGUIAP_Import_U_OBJTYPE]
GO


